### ISSUE TITLE
No try it buttons - eager loading include

### ISSUE THREAD

**Issue by eliassal** [entityframeworktutorial/EF6-DBFirst-Demo#2]
Hi, I find your tutorials are very useful and easy to follow. I followed the LINQ tuto at https://www.tutorialsteacher.com/linq/linq-projection-operators
I find that Try it button is a very good idea to see the whole querying/displaying which is missing in this one. For example, in Querying > Eager Loading, we can see how to retrieve data and do a "include standards" but no code that shows how loop through the result and display the information. I googled and tried several things but not able to understand how this can be done
Thanks for your help

**Comment by entityframeworktutorial** [comment]
Not related to entity framework so closing this issue.
